name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Dependencies
        run: flutter pub get

      - name: Build iOS Application (Unsigned)
        run: flutter build ios --no-codesign --release --build-number=1 CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM=""

      - name: Package Unsigned IPA
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r 2Play_Unsigned.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2Play-iOS-Unsigned-IPA
          path: 2Play_Unsigned.ipa
